-- V98：去掉业务表主键 AUTO_INCREMENT（雪花 ID 由应用 ASSIGN_ID 生成）
-- 幂等：重复执行仅再次 MODIFY 列定义

ALTER TABLE `user` MODIFY COLUMN `id` BIGINT NOT NULL COMMENT '主键';
ALTER TABLE `sys_sms_config` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `sys_message` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `screening_school` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `screening_key_population` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `screening_close_contact` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `close_contact_case` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `latent_infection` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `notice` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `supervision_form` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `latent_follow_up` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `latent_check` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `patient` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `first_visit` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `follow_up_visit` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `medication_management` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `medication_pickup` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `epidemic_report` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `permission` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `role_permission` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `department` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `referral` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `user_permission` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `operation_log` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `referral_tracking` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `epidemic_import` MODIFY COLUMN `id` BIGINT NOT NULL;
ALTER TABLE `questionnaire_config` MODIFY COLUMN `id` BIGINT NOT NULL;
