/** 密接个案表 — 线上预览列定义（与73列Excel模板字段对应） */
export interface CloseContactCaseColumn {
  field: string
  title: string
  width: number
  fixed?: "left" | "right"
}

export const DIAGNOSIS_RESULT_OPTIONS = [
  { label: "活动性肺结核", value: "活动性肺结核" },
  { label: "潜伏感染者", value: "潜伏感染者" },
  { label: "未做", value: "未做" },
  { label: "未发现异常", value: "未发现异常" }
] as const

/** 电子表格预览列（横向滚动展示全部字段） */
export const CLOSE_CONTACT_CASE_COLUMNS: CloseContactCaseColumn[] = [
  { field: "creatorUsername", title: "录入用户", width: 110, fixed: "left" },
  { field: "name", title: "接触者姓名", width: 100, fixed: "left" },
  { field: "idNumber", title: "接触者身份证号", width: 180, fixed: "left" },
  { field: "city", title: "市/州", width: 100 },
  { field: "district", title: "区/县", width: 100 },
  { field: "sourcePatientName", title: "原患者姓名", width: 110 },
  { field: "sourcePatientCaseNo", title: "原患者病案号", width: 120 },
  { field: "sourcePatientBacteriologyResult", title: "原患者病原学结果", width: 140 },
  { field: "sourcePatientPhone", title: "原患者电话", width: 120 },
  { field: "sourcePatientIdNumber", title: "原患者身份证号", width: 180 },
  { field: "reportDate", title: "填表日期", width: 110 },
  { field: "registrationDate", title: "密接登记日期", width: 120 },
  { field: "age", title: "年龄", width: 70 },
  { field: "phone", title: "联系电话", width: 120 },
  { field: "gender", title: "性别", width: 70 },
  { field: "ethnicity", title: "民族", width: 80 },
  { field: "contactType", title: "接触类型", width: 100 },
  { field: "contactPlace", title: "接触场所", width: 110 },
  { field: "firstScreenDate", title: "首次筛查日期", width: 120 },
  { field: "symptom1", title: "结核症状1", width: 110 },
  { field: "symptom2", title: "结核症状2", width: 110 },
  { field: "infectionCheckDate", title: "感染检测日期", width: 120 },
  { field: "infectionCheckMethod", title: "感染检测方法", width: 120 },
  { field: "infectionCheckResult", title: "感染检测结果", width: 120 },
  { field: "imagingDate", title: "影像检查日期", width: 120 },
  { field: "imagingMethod", title: "影像方法", width: 110 },
  { field: "imagingResult", title: "影像结果", width: 110 },
  { field: "sputumCheckDate", title: "痰检留标日期", width: 120 },
  { field: "sputumCheckMethod", title: "痰检方法", width: 110 },
  { field: "sputumCheckResult", title: "痰检结果", width: 110 },
  { field: "finalScreeningResult", title: "诊断结果", width: 130 },
  { field: "hasContraindication", title: "有无禁忌症", width: 110 },
  { field: "noTreatmentReason", title: "不接受预防治疗原因", width: 150 },
  { field: "contraindicationRemark", title: "禁忌症备注", width: 120 },
  { field: "hasPreventiveTreatment", title: "是否开展预防治疗", width: 140 },
  { field: "preventivePlan", title: "预防性治疗方案", width: 130 },
  { field: "preventivePlanRemark", title: "其他方案备注", width: 120 },
  { field: "treatmentCompleted", title: "是否完成治疗", width: 120 },
  { field: "incompleteReason", title: "未完成原因", width: 120 },
  { field: "followup6DueDate", title: "6月随访到期", width: 120 },
  { field: "followup6ScreenDate", title: "6月筛查日期", width: 120 },
  { field: "followup6Symptom1", title: "6月-症状1", width: 110 },
  { field: "followup6Symptom2", title: "6月-症状2", width: 110 },
  { field: "followup6ImagingDate", title: "6月-影像日期", width: 120 },
  { field: "followup6ImagingMethod", title: "6月-影像方法", width: 120 },
  { field: "followup6ImagingResult", title: "6月-影像结果", width: 120 },
  { field: "followup6SputumDate", title: "6月-痰检日期", width: 120 },
  { field: "followup6SputumMethod", title: "6月-病原学方法", width: 130 },
  { field: "followup6SputumResult", title: "6月-病原学结果", width: 130 },
  { field: "followup6Result", title: "6月随访结果", width: 120 },
  { field: "followup12DueDate", title: "12月随访到期", width: 120 },
  { field: "followup12ScreenDate", title: "12月筛查日期", width: 120 },
  { field: "followup12Symptom1", title: "12月-症状1", width: 110 },
  { field: "followup12Symptom2", title: "12月-症状2", width: 110 },
  { field: "followup12ImagingDate", title: "12月-影像日期", width: 120 },
  { field: "followup12ImagingMethod", title: "12月-影像方法", width: 120 },
  { field: "followup12ImagingResult", title: "12月-影像结果", width: 120 },
  { field: "followup12SputumDate", title: "12月-痰检日期", width: 120 },
  { field: "followup12SputumMethod", title: "12月-病原学方法", width: 130 },
  { field: "followup12SputumResult", title: "12月-病原学结果", width: 130 },
  { field: "followup12Result", title: "12月随访结果", width: 120 },
  { field: "followup24DueDate", title: "24月随访到期", width: 120 },
  { field: "followup24ScreenDate", title: "24月筛查日期", width: 120 },
  { field: "followup24Symptom1", title: "24月-症状1", width: 110 },
  { field: "followup24Symptom2", title: "24月-症状2", width: 110 },
  { field: "followup24ImagingDate", title: "24月-影像日期", width: 120 },
  { field: "followup24ImagingMethod", title: "24月-影像方法", width: 120 },
  { field: "followup24ImagingResult", title: "24月-影像结果", width: 120 },
  { field: "followup24SputumDate", title: "24月-痰检日期", width: 120 },
  { field: "followup24SputumMethod", title: "24月-病原学方法", width: 130 },
  { field: "followup24SputumResult", title: "24月-病原学结果", width: 130 },
  { field: "followup24Result", title: "24月随访结果", width: 120 },
  { field: "remark", title: "备注", width: 150 },
  { field: "createTime", title: "录入时间", width: 160 }
]
