export {
  closeCaseApi,
  confirmNoticeApi,
  exportLatentListApi,
  getCheckListApi,
  getFollowUpListApi,
  getLatentListApi,
  getNoticeDetailApi,
  getNoticeListByBizApi,
  getSupervisionDetailApi,
  importXrayApi,
  referralLatentApi,
  saveCheckApi,
  saveFollowUpApi,
  saveSupervisionApi,
  sendNoticeApi,
  setMedicationStatusApi,
  submitXrayApi,
  trackLatentApi
} from "@/pages/school/latent/apis"
